spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_prod?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver